<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActivityLogTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_log')->delete();
        
        \DB::table('activity_log')->insert(array (
            0 => 
            array (
                'id' => 1,
                'log_name' => 'default',
                'description' => 'Admin Loged In',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"Log_In"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:28:26',
                'updated_at' => '2025-08-30 19:28:26',
            ),
            1 => 
            array (
                'id' => 2,
                'log_name' => 'default',
                'description' => 'addsupervisor',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addsupervisor"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:30:02',
                'updated_at' => '2025-08-30 19:30:02',
            ),
            2 => 
            array (
                'id' => 3,
                'log_name' => 'default',
                'description' => 'Admin Send Forget Password Code',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"Send Forget Password Code"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:30:22',
                'updated_at' => '2025-08-30 19:30:22',
            ),
            3 => 
            array (
                'id' => 4,
                'log_name' => 'default',
                'description' => 'Admin Send Forget Password Code',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"Send Forget Password Code"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:30:46',
                'updated_at' => '2025-08-30 19:30:46',
            ),
            4 => 
            array (
                'id' => 5,
                'log_name' => 'default',
                'description' => 'get_education_level_data',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"get_education_level_data"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:31:29',
                'updated_at' => '2025-08-30 19:31:29',
            ),
            5 => 
            array (
                'id' => 6,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:35:08',
                'updated_at' => '2025-08-30 19:35:08',
            ),
            6 => 
            array (
                'id' => 7,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:35:18',
                'updated_at' => '2025-08-30 19:35:18',
            ),
            7 => 
            array (
                'id' => 8,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:35:26',
                'updated_at' => '2025-08-30 19:35:26',
            ),
            8 => 
            array (
                'id' => 9,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:35:39',
                'updated_at' => '2025-08-30 19:35:39',
            ),
            9 => 
            array (
                'id' => 10,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:35:47',
                'updated_at' => '2025-08-30 19:35:47',
            ),
            10 => 
            array (
                'id' => 11,
                'log_name' => 'default',
                'description' => ' Add class Education Level ',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":" Add class Education Level "}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:36:01',
                'updated_at' => '2025-08-30 19:36:01',
            ),
            11 => 
            array (
                'id' => 12,
                'log_name' => 'default',
                'description' => 'addparent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addparent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:36:30',
                'updated_at' => '2025-08-30 19:36:30',
            ),
            12 => 
            array (
                'id' => 13,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:40:45',
                'updated_at' => '2025-08-30 19:40:45',
            ),
            13 => 
            array (
                'id' => 14,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:41:01',
                'updated_at' => '2025-08-30 19:41:01',
            ),
            14 => 
            array (
                'id' => 15,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:41:11',
                'updated_at' => '2025-08-30 19:41:11',
            ),
            15 => 
            array (
                'id' => 16,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:41:22',
                'updated_at' => '2025-08-30 19:41:22',
            ),
            16 => 
            array (
                'id' => 17,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:41:32',
                'updated_at' => '2025-08-30 19:41:32',
            ),
            17 => 
            array (
                'id' => 18,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:41:41',
                'updated_at' => '2025-08-30 19:41:41',
            ),
            18 => 
            array (
                'id' => 19,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:42:06',
                'updated_at' => '2025-08-30 19:42:06',
            ),
            19 => 
            array (
                'id' => 20,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:42:13',
                'updated_at' => '2025-08-30 19:42:13',
            ),
            20 => 
            array (
                'id' => 21,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:42:22',
                'updated_at' => '2025-08-30 19:42:22',
            ),
            21 => 
            array (
                'id' => 22,
                'log_name' => 'default',
                'description' => 'addstudent',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addstudent"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:42:35',
                'updated_at' => '2025-08-30 19:42:35',
            ),
            22 => 
            array (
                'id' => 23,
                'log_name' => 'default',
                'description' => 'addlibrarian',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"Process_type":"addlibrarian"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:42:44',
                'updated_at' => '2025-08-30 19:42:44',
            ),
            23 => 
            array (
                'id' => 24,
                'log_name' => 'default',
                'description' => 'Librarianlibrarianbase Send Forget Password Code',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Send login Code for librarian Code"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:43:05',
                'updated_at' => '2025-08-30 19:43:05',
            ),
            24 => 
            array (
                'id' => 25,
                'log_name' => 'default',
                'description' => 'librarianlibrarianbase Loged In',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_role":"librarian","Process_type":"Log_In librarian"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:43:41',
                'updated_at' => '2025-08-30 19:43:41',
            ),
            25 => 
            array (
                'id' => 26,
                'log_name' => 'default',
                'description' => 'Adding Textual Book',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Textual Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:44:17',
                'updated_at' => '2025-08-30 19:44:17',
            ),
            26 => 
            array (
                'id' => 27,
                'log_name' => 'default',
                'description' => 'Adding Textual Book',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Textual Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:44:49',
                'updated_at' => '2025-08-30 19:44:49',
            ),
            27 => 
            array (
                'id' => 28,
                'log_name' => 'default',
                'description' => 'Adding Textual Book',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Textual Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:44:57',
                'updated_at' => '2025-08-30 19:44:57',
            ),
            28 => 
            array (
                'id' => 29,
                'log_name' => 'default',
                'description' => 'Adding Cultural',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Cultural Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:45:19',
                'updated_at' => '2025-08-30 19:45:19',
            ),
            29 => 
            array (
                'id' => 30,
                'log_name' => 'default',
                'description' => 'Adding Cultural',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Cultural Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:45:30',
                'updated_at' => '2025-08-30 19:45:30',
            ),
            30 => 
            array (
                'id' => 31,
                'log_name' => 'default',
                'description' => 'Adding Cultural',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Cultural Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:45:40',
                'updated_at' => '2025-08-30 19:45:40',
            ),
            31 => 
            array (
                'id' => 32,
                'log_name' => 'default',
                'description' => 'Adding Cultural',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Cultural Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:45:50',
                'updated_at' => '2025-08-30 19:45:50',
            ),
            32 => 
            array (
                'id' => 33,
                'log_name' => 'default',
                'description' => 'Adding Cultural',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Adding Cultural Book","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:01',
                'updated_at' => '2025-08-30 19:46:01',
            ),
            33 => 
            array (
                'id' => 34,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:34',
                'updated_at' => '2025-08-30 19:46:34',
            ),
            34 => 
            array (
                'id' => 35,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:41',
                'updated_at' => '2025-08-30 19:46:41',
            ),
            35 => 
            array (
                'id' => 36,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:48',
                'updated_at' => '2025-08-30 19:46:48',
            ),
            36 => 
            array (
                'id' => 37,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:53',
                'updated_at' => '2025-08-30 19:46:53',
            ),
            37 => 
            array (
                'id' => 38,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:46:57',
                'updated_at' => '2025-08-30 19:46:57',
            ),
            38 => 
            array (
                'id' => 39,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:03',
                'updated_at' => '2025-08-30 19:47:03',
            ),
            39 => 
            array (
                'id' => 40,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:07',
                'updated_at' => '2025-08-30 19:47:07',
            ),
            40 => 
            array (
                'id' => 41,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:12',
                'updated_at' => '2025-08-30 19:47:12',
            ),
            41 => 
            array (
                'id' => 42,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:19',
                'updated_at' => '2025-08-30 19:47:19',
            ),
            42 => 
            array (
                'id' => 43,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:34',
                'updated_at' => '2025-08-30 19:47:34',
            ),
            43 => 
            array (
                'id' => 44,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:42',
                'updated_at' => '2025-08-30 19:47:42',
            ),
            44 => 
            array (
                'id' => 45,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:47:47',
                'updated_at' => '2025-08-30 19:47:47',
            ),
            45 => 
            array (
                'id' => 46,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:03',
                'updated_at' => '2025-08-30 19:48:03',
            ),
            46 => 
            array (
                'id' => 47,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:07',
                'updated_at' => '2025-08-30 19:48:07',
            ),
            47 => 
            array (
                'id' => 48,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:12',
                'updated_at' => '2025-08-30 19:48:12',
            ),
            48 => 
            array (
                'id' => 49,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:18',
                'updated_at' => '2025-08-30 19:48:18',
            ),
            49 => 
            array (
                'id' => 50,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:22',
                'updated_at' => '2025-08-30 19:48:22',
            ),
            50 => 
            array (
                'id' => 51,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:27',
                'updated_at' => '2025-08-30 19:48:27',
            ),
            51 => 
            array (
                'id' => 52,
                'log_name' => 'default',
                'description' => 'Making Book Buy',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Buy","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:48:34',
                'updated_at' => '2025-08-30 19:48:34',
            ),
            52 => 
            array (
                'id' => 53,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:49:17',
                'updated_at' => '2025-08-30 19:49:17',
            ),
            53 => 
            array (
                'id' => 54,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:49:31',
                'updated_at' => '2025-08-30 19:49:31',
            ),
            54 => 
            array (
                'id' => 55,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:54:01',
                'updated_at' => '2025-08-30 19:54:01',
            ),
            55 => 
            array (
                'id' => 56,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:54:27',
                'updated_at' => '2025-08-30 19:54:27',
            ),
            56 => 
            array (
                'id' => 57,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:55:23',
                'updated_at' => '2025-08-30 19:55:23',
            ),
            57 => 
            array (
                'id' => 58,
                'log_name' => 'default',
                'description' => 'Making Book Loan',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Loan","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:57:12',
                'updated_at' => '2025-08-30 19:57:12',
            ),
            58 => 
            array (
                'id' => 59,
                'log_name' => 'default',
                'description' => 'Making Book Return',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Return","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:57:35',
                'updated_at' => '2025-08-30 19:57:35',
            ),
            59 => 
            array (
                'id' => 60,
                'log_name' => 'default',
                'description' => 'Making Book Return',
                'subject_type' => NULL,
                'event' => NULL,
                'subject_id' => NULL,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 14,
                'properties' => '{"Process_type":"Making Book Return","date":"2025-08-30"}',
                'batch_uuid' => NULL,
                'created_at' => '2025-08-30 19:57:42',
                'updated_at' => '2025-08-30 19:57:42',
            ),
        ));
        
        
    }
}