<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MarksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('marks')->delete();
        
        \DB::table('marks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'student_id' => 1,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:11',
                'updated_at' => '2025-09-06 01:30:11',
            ),
            1 => 
            array (
                'id' => 2,
                'student_id' => 1,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:21',
                'updated_at' => '2025-09-06 01:30:21',
            ),
            2 => 
            array (
                'id' => 3,
                'student_id' => 2,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:31',
                'updated_at' => '2025-09-06 01:30:31',
            ),
            3 => 
            array (
                'id' => 4,
                'student_id' => 3,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:38',
                'updated_at' => '2025-09-06 01:30:38',
            ),
            4 => 
            array (
                'id' => 5,
                'student_id' => 4,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:44',
                'updated_at' => '2025-09-06 01:30:44',
            ),
            5 => 
            array (
                'id' => 6,
                'student_id' => 5,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:48',
                'updated_at' => '2025-09-06 01:30:48',
            ),
            6 => 
            array (
                'id' => 7,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:30:54',
                'updated_at' => '2025-09-06 01:30:54',
            ),
            7 => 
            array (
                'id' => 8,
                'student_id' => 7,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:31:00',
                'updated_at' => '2025-09-06 01:31:00',
            ),
            8 => 
            array (
                'id' => 9,
                'student_id' => 8,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:31:05',
                'updated_at' => '2025-09-06 01:31:05',
            ),
            9 => 
            array (
                'id' => 10,
                'student_id' => 8,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'homework',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:33:10',
                'updated_at' => '2025-09-06 01:33:10',
            ),
            10 => 
            array (
                'id' => 11,
                'student_id' => 8,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'activity',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:33:19',
                'updated_at' => '2025-09-06 01:33:19',
            ),
            11 => 
            array (
                'id' => 12,
                'student_id' => 8,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:33:28',
                'updated_at' => '2025-09-06 01:33:28',
            ),
            12 => 
            array (
                'id' => 13,
                'student_id' => 7,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:33:41',
                'updated_at' => '2025-09-06 01:33:41',
            ),
            13 => 
            array (
                'id' => 14,
                'student_id' => 7,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'homework',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:33:52',
                'updated_at' => '2025-09-06 01:33:52',
            ),
            14 => 
            array (
                'id' => 15,
                'student_id' => 7,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'activity',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:34:01',
                'updated_at' => '2025-09-06 01:34:01',
            ),
            15 => 
            array (
                'id' => 16,
                'student_id' => 7,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'quiz',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:34:17',
                'updated_at' => '2025-09-06 01:34:17',
            ),
            16 => 
            array (
                'id' => 17,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'quiz',
                'score' => 9,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:34:41',
                'updated_at' => '2025-09-06 01:34:41',
            ),
            17 => 
            array (
                'id' => 18,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 4,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:34:53',
                'updated_at' => '2025-09-06 01:34:53',
            ),
            18 => 
            array (
                'id' => 19,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 8,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:35:07',
                'updated_at' => '2025-09-06 01:35:07',
            ),
            19 => 
            array (
                'id' => 20,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'homework',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:35:20',
                'updated_at' => '2025-09-06 01:35:20',
            ),
            20 => 
            array (
                'id' => 21,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'activity',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:35:27',
                'updated_at' => '2025-09-06 01:35:27',
            ),
            21 => 
            array (
                'id' => 22,
                'student_id' => 6,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'activity',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:35:34',
                'updated_at' => '2025-09-06 01:35:34',
            ),
            22 => 
            array (
                'id' => 23,
                'student_id' => 5,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'quiz',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:36:02',
                'updated_at' => '2025-09-06 01:36:02',
            ),
            23 => 
            array (
                'id' => 24,
                'student_id' => 5,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'midterm',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:36:25',
                'updated_at' => '2025-09-06 01:36:25',
            ),
            24 => 
            array (
                'id' => 25,
                'student_id' => 5,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:36:41',
                'updated_at' => '2025-09-06 01:36:41',
            ),
            25 => 
            array (
                'id' => 26,
                'student_id' => 5,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'homework',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:36:50',
                'updated_at' => '2025-09-06 01:36:50',
            ),
            26 => 
            array (
                'id' => 27,
                'student_id' => 1,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'homework',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:37:18',
                'updated_at' => '2025-09-06 01:37:18',
            ),
            27 => 
            array (
                'id' => 28,
                'student_id' => 1,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'final',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:37:32',
                'updated_at' => '2025-09-06 01:37:32',
            ),
            28 => 
            array (
                'id' => 29,
                'student_id' => 1,
                'teacher_id' => 1,
                'term_id' => 1,
                'exam_type' => 'activity',
                'score' => 7,
                'max_score' => 10,
                'date' => '2025-09-06',
                'teacher_note' => 'good',
                'created_at' => '2025-09-06 01:37:51',
                'updated_at' => '2025-09-06 01:37:51',
            ),
        ));
        
        
    }
}